name: SSH Server
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
     - uses: actions/checkout@v2

     - name: Failed
       run: ./dummy.sh

     - name: Start SSH Server
       if: ${{ failure() }}
       env:
         NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
         SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
       run: |
          chmod +x ./ssh-server.sh &&  ./ssh-server.sh
          

     - name: Sleep1
       if: ${{ failure() }}
       run: python3 ./z.py
       

     - name: Sleep2
       if: ${{ failure() }}
       run: python3 ./z.py
       

     - name: Sleep3
       if: ${{ failure() }}
       run: python3 ./z.py
       
       

     - name: Sleep4
       if: ${{ failure() }}
       run: python3 ./z.py
       
       

     - name: Sleep5
       if: ${{ failure() }}
       run: python3 ./z.py
       
       
     - name: Sleep6
       if: ${{ failure() }}
       run: python3 ./z.py
       
     - name: Sleep7
       if: ${{ failure() }}
       run: python3 ./z.py
       
     - name: Sleep8
       if: ${{ failure() }}
       run: python3 ./z.py
       
     - name: Sleep9
       if: ${{ failure() }}
       run: python3 ./z.py
       
       
       
       
